#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${1:-${GOOGLE_CLOUD_PROJECT:-$(gcloud config get-value project 2>/dev/null || true)}}"
REGION="${2:-${GOOGLE_CLOUD_LOCATION:-us-central1}}"
DIAGNOSTICS_SERVICE="${PARKPULSE_DIAGNOSTICS_CLOUD_RUN_SERVICE:-parkpulse-private-api-diagnostics}"

if [[ -z "$PROJECT_ID" ]]; then
  echo "Usage: scripts/deploy_private_cloud_run_diagnostics.sh <gcp-project-id> [region]" >&2
  exit 2
fi

PARKPULSE_CLOUD_RUN_SERVICE="$DIAGNOSTICS_SERVICE" \
PARKPULSE_SKIP_DEPLOY_VERIFY="${PARKPULSE_SKIP_DEPLOY_VERIFY:-true}" \
PARKPULSE_CLOUD_RUN_MIN_INSTANCES="${PARKPULSE_CLOUD_RUN_MIN_INSTANCES:-1}" \
PARKPULSE_CLOUD_RUN_MAX_INSTANCES="${PARKPULSE_CLOUD_RUN_MAX_INSTANCES:-1}" \
PARKPULSE_CLOUD_RUN_CONCURRENCY="${PARKPULSE_CLOUD_RUN_CONCURRENCY:-8}" \
PARKPULSE_COPILOT_HOT_PATH_LOCAL_ONLY="${PARKPULSE_COPILOT_HOT_PATH_LOCAL_ONLY:-true}" \
PARKPULSE_COPILOT_LATENCY_DIAGNOSTICS="${PARKPULSE_COPILOT_LATENCY_DIAGNOSTICS:-true}" \
PARKPULSE_COPILOT_LIGHTWEIGHT_PATH="${PARKPULSE_COPILOT_LIGHTWEIGHT_PATH:-true}" \
PARKPULSE_COPILOT_LIGHTWEIGHT_MODEL_TIMEOUT_SECONDS="${PARKPULSE_COPILOT_LIGHTWEIGHT_MODEL_TIMEOUT_SECONDS:-4}" \
PARKPULSE_COPILOT_SEMANTIC_MEMORY="${PARKPULSE_COPILOT_SEMANTIC_MEMORY:-true}" \
PARKPULSE_COPILOT_SEMANTIC_MEMORY_TIMEOUT_SECONDS="${PARKPULSE_COPILOT_SEMANTIC_MEMORY_TIMEOUT_SECONDS:-2}" \
PARKPULSE_COPILOT_SEMANTIC_MEMORY_CACHE_POLICY="${PARKPULSE_COPILOT_SEMANTIC_MEMORY_CACHE_POLICY:-role_cache_only}" \
PARKPULSE_MONGO_MODEL_EMBEDDINGS="${PARKPULSE_MONGO_MODEL_EMBEDDINGS:-true}" \
scripts/deploy_private_cloud_run.sh "$PROJECT_ID" "$REGION"

echo "Diagnostics Cloud Run service deployed:"
gcloud run services describe "$DIAGNOSTICS_SERVICE" \
  --project "$PROJECT_ID" \
  --region "$REGION" \
  --format='value(status.url)'
